import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { loadEnvFile } from 'node:process';

const envFile = new URL('../.env', import.meta.url);
if (existsSync(envFile)) {
  loadEnvFile(envFile);
}

const backendUrl = process.env.BACKEND_URL?.trim().replace(/\/+$/, '');
if (!backendUrl) {
  throw new Error('Set BACKEND_URL in frontend/.env (see .env.example) or in the build environment.');
}

const parsedUrl = new URL(backendUrl);
if (!['http:', 'https:'].includes(parsedUrl.protocol) || parsedUrl.search || parsedUrl.hash) {
  throw new Error('BACKEND_URL must be an HTTP(S) base URL without a query or fragment.');
}

const directory = new URL('../src/environments/', import.meta.url);
mkdirSync(directory, { recursive: true });
writeFileSync(
  new URL('environment.ts', directory),
  '// Generated by scripts/load-env.mjs. Edit .env instead.\n' +
    'export const environment = ' + JSON.stringify({ backendUrl }, null, 2) + ';\n',
);
